# Application
spring.application.name=backend-video

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/logoped_db?encoding=UTF-8
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# File Upload
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Jitsi Meet
# Для локальной разработки используем публичный сервер meet.jit.si
# Для продакшена заменить на свой сервер
#jitsi.url=https://meet.jit.si
jitsi.url=https://200.87.154.47:8443
jitsi.jwt.app-id=logopedic_app
jitsi.jwt.app-secret=logopedic_secret_key_min_32_chars_for_security

# Port
server.port=8081
